name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack for Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      # core 디렉토리로 이동하여 빌드 및 배포 작업 수행
      - name: Change directory to core
        working-directory: ./core
        run: |
          yarn build

      - name: Publish core to npm
        working-directory: ./core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
